import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { parse } from "yaml";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const yaml = readFileSync(join(root, "content.yaml"), "utf-8");
const data = parse(yaml);

const output = `// AUTO-GENERATED from content.yaml — do not edit this file directly.
// Edit content.yaml then run:  npm run content:generate
/* eslint-disable */

const content = ${JSON.stringify(data, null, 2)} as const;

export default content;
`;

writeFileSync(join(root, "lib", "content.generated.ts"), output);
console.log("content.generated.ts updated from content.yaml");
